// $Id: Langname_Scanner.hh,v 1.1 2008/04/06 17:10:46 eric Exp $

#ifndef shex_parse_to_XMLScanner_H
#define shex_parse_to_XMLScanner_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define	YY_DECL						\
    shexParseToXml::shexParseToXmlParser::token_type				\
    shexParseToXml::shexParseToXmlScanner::lex(				\
	shexParseToXml::shexParseToXmlParser::semantic_type* yylval,		\
	shexParseToXml::shexParseToXmlParser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer shexParseToXmlFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "shex-parse-to-XMLParser.hh"

namespace shexParseToXml {

/** shexParseToXmlScanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to shexParseToXmlFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the shexParseToXmlScanner class. This is required
 * because the yylex() defined in shexParseToXmlFlexLexer has no parameters. */
class shexParseToXmlScanner : public shexParseToXmlFlexLexer
{
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    shexParseToXmlScanner(std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~shexParseToXmlScanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual shexParseToXmlParser::token_type lex(
	shexParseToXmlParser::semantic_type* yylval,
	shexParseToXmlParser::location_type* yylloc
	);

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);
};

} // namespace shexParseToXml

#endif // shex_parse_to_XMLScanner_H
